export const SET_SETTINGS_LOADING = 'SET_SETTINGS_LOADING';

export const GET_USER_ACCOUNT_SUCCESS = 'GET_USER_ACCOUNT_SUCCESS';

export const GET_USER_SIGNATURE_SUCCESS = 'GET_USER_SIGNATURE_SUCCESS';

export const SET_IS_CREATED = 'SET_IS_CREATED';

export const SET_ARTIST_SETTINGS = 'SET_ARTIST_SETTINGS';
