export const SET_SOCIAL_MEDIA_LOADING = 'SET_SOCIAL_MEDIA_LOADING';

export const GET_SOCIAL_MEDIA_DATA_SUCCESS = 'GET_SOCIAL_MEDIA_DATA_SUCCESS';

export const SET_SOCIAL_MEDIA_COUNTRY = 'SET_SOCIAL_MEDIA_COUNTRY';

export const SET_SOCIAL_MEDIA_LINK = 'SET_SOCIAL_MEDIA_LINK';

export const DELETE_SOCIAL_MEDIA_DATA_SUCCESS = 'DELETE_SOCIAL_MEDIA_DATA_SUCCESS';
