export const SET_ATELIER_POSTS = 'SET_ATELIER_POSTS'
export const SET_FILTERS = 'SET_FILTERS'
export const DELETE_POST_BY_MASTER = 'DELETE_POST_BY_MASTER';
export const MASTER_UPDATE_ATELIER = 'MASTER_UPDATE_ATELIER'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const UPDATE_TITLES_BY_MASTER = 'UPDATE_TITLES_BY_MASTER';
