export const SET_MASTER_ARTIST_ACCOUNT_LOADING = 'SET_MASTER_ARTIST_ACCOUNT_LOADING';

export const GET_MASTER_ARTIST_ACCOUNT_SUCCESS = 'GET_MASTER_ARTIST_ACCOUNT_SUCCESS';

export const RESET_MASTER_ARTIST_ACCOUNT = 'RESET_MASTER_ARTIST_ACCOUNT';
