export const SET_PERMISSION_USERS = 'SET_PERMISSION_USERS';

export const UPDATE_USER_PERMISSION = 'UPDATE_USER_PERMISSION';

export const SET_PERMISSION_FILTERS = 'SET_PERMISSION_FILTERS';

export const SET_ACCESS_FILTERS = 'SET_ACCESS_FILTERS';

export const SET_SEARCH_FILTERS = 'SET_SEARCH_FILTERS';
