export const SET_BACKGROUNDS_LOADING = 'SET_BACKGROUNDS_LOADING';

export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export const GET_BACKGROUNDS_SUCCESS = 'GET_BACKGROUNDS_SUCCESS';

export const GET_BACKGROUNDS_ERROR = 'GET_BACKGROUNDS_ERROR';

export const DELETE_BACKGROUND_DIALOG = 'DELETE_BACKGROUND_DIALOG';

export const DELETE_BACKGROUND_SUCCESS = 'DELETE_BACKGROUND_SUCCESS';

export const DELETE_BACKGROUND_ERROR = 'DELETE_BACKGROUND_ERROR';

export const UPLOAD_BACKGROUND_SUCCESS = 'UPLOAD_BACKGROUND_SUCCESS';

export const UPLOAD_BACKGROUND_ERROR = 'UPLOAD_BACKGROUND_ERROR';
