export const SET_MASTER_STATISTICS_LOADING = 'SET_MASTER_STATISTICS_LOADING';

export const SET_MASTER_STATISTICS_INITIAL_LOADING = 'SET_MASTER_STATISTICS_INITIAL_LOADING';

export const GET_MASTER_STATISTICS_DATA_SUCCESS = 'GET_MASTER_STATISTICS_DATA_SUCCESS';

export const SET_MASTER_STATISTICS_DATA_FILTER = 'SET_MASTER_STATISTICS_DATA_FILTER';

export const SET_MASTER_STATISTICS_DATA_DATE_FILTER = 'SET_MASTER_STATISTICS_DATA_DATE_FILTER';

export const SET_MASTER_STATISTICS_DATA_OPTIONS_FILTER = 'SET_MASTER_STATISTICS_DATA_OPTIONS_FILTER';
