export const SET_MODALS_LOADING = 'SET_MODALS_LOADING';

export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export const GET_MODAL_IMGS_SUCCESS = 'GET_MODAL_IMGS_SUCCESS';

export const GET_MODAL_IMGS_ERROR = 'GET_MODAL_IMGS_ERROR';

export const DELETE_MODAL_IMG_DIALOG = 'DELETE_MODAL_IMG_DIALOG';

export const DELETE_MODAL_IMG_SUCCESS = 'DELETE_MODAL_IMG_SUCCESS';

export const DELETE_MODAL_IMG_ERROR = 'DELETE_MODAL_IMG_ERROR';

export const UPLOAD_MODAL_IMG_SUCCESS = 'UPLOAD_MODAL_IMG_SUCCESS';

export const UPLOAD_MODAL_IMG_ERROR = 'UPLOAD_MODAL_IMG_ERROR';

export const GET_MODALS_SUCCESS = 'GET_MODALS_SUCCESS';

export const GET_MODALS_ERROR = 'GET_MODALS_ERROR';

export const GET_MODAL_CONTENT_SUCCESS = 'GET_MODAL_CONTENT_SUCCESS';

export const GET_MODAL_CONTENT_ERROR = 'GET_MODAL_CONTENT_ERROR';

export const SELECT_MODAL = 'SELECT_MODAL';

export const SET_MODALS_PAGE = 'SET_MODALS_PAGE';

export const CHANGE_MODAL_DESCRIPTION = 'CHANGE_MODAL_DESCRIPTION';

export const UPDATE_MODAL_DESCRIPTION_SUCCESS = 'UPDATE_MODAL_DESCRIPTION_SUCCESS';

export const UPDATE_MODAL_DESCRIPTION_ERROR = 'UPDATE_MODAL_DESCRIPTION_ERROR';

export const REMOVE_IMAGE_FROM_MODAL = 'REMOVE_IMAGE_FROM_MODAL';

export const ADD_IMAGE_TO_MODAL = 'ADD_IMAGE_TO_MODAL';
