export const SET_PUBLIC_ARTWORKS_LOADING = 'SET_PUBLIC_ARTWORKS_LOADING';

export const SET_PUBLIC_ARTWORKS_CHECKED = 'SET_PUBLIC_ARTWORKS_CHECKED';

export const SET_PUBLIC_ARTWORKS_PAGE = 'SET_PUBLIC_ARTWORKS_PAGE';

export const SET_PUBLIC_ARTWORKS_SEARCH = 'SET_PUBLIC_ARTWORKS_SEARCH';

export const GET_PUBLIC_ARTWORKS_SUCCESS = 'GET_PUBLIC_ARTWORKS_SUCCESS';

export const GET_PUBLIC_ARTWORKS_STATE_FROM_COOKIES = 'GET_PUBLIC_ARTWORKS_STATE_FROM_COOKIES';

export const RESET = 'RESET';
