export const SET_INITIAL_VALUE_OF_ANSWERS = 'SET_INITIAL_VALUE_OF_ANSWERS';
export const GET_INTERVIEW = 'GET_INTERVIEW';
export const GET_INTERVIEW_PHOTO = 'GET_INTERVIEW_PHOTO';
export const SET_LOADING_AVATAR = 'SET_LOADING_AVATAR';

